SELECT * FROM HR.employees;

SELECT employee_id+1, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM HR.employees
WHERE MANAGER_ID IN (101,145,149);

SELECT employee_id+1, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM HR.employees
WHERE FIRST_NAME LIKE '%s%';

SELECT employee_id+1, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM HR.employees
WHERE SALARY BETWEEN 2500 AND 5000;

INSERT INTO JOGADOR
(ID_JOGADOR,NOME, POSICAO, NICKNAME)
VALUES
(1, 'JOGADOR 1', 2, 'JOGADOR TÁTICO');

SELECT * FROM JOGADOR;

INSERT INTO JOGADOR
(ID_JOGADOR, NOME, POSICAO, NICKNAME)
VALUES
(2, 'JOGADOR 2', 1 ,'JOGADOR BOM');

INSERT INTO CONTRATADO
(ID_JOGADOR, DATA_INICIO, DATA_FIM)
VALUES
(1, TO_DATE('09-02-2021'), TO_DATE('09-02-2022'));

SELECT * FROM JOGADOR;

UPDATE JOGADOR
SET nome = 'ALEXANDER', POSICAO = 5
WHERE ID_JOGADOR = 1;

DELETE FROM CONTRATADO
WHERE ID_JOGADOR = 2